---
title: "visualizations_for_final_blog"
format: html
editor: visual
---

# Pie Chart bio sex question 5
```{r}
library(gridExtra)

make_pie_chart <- function(slices, title){

lbls <- c("No Risk", "Slight", "Moderate", "Great", "NA")
pct <- round(slices/sum(slices)*100)
lbls <- paste(lbls, pct)
# add percents to labels
lbls <- paste(lbls,"%",sep="") # ad % to labels
pie(slices,labels = lbls, col=rainbow(length(lbls)),
   main= title) 
}

make_pie_chart(c(11.89, 3.14, 9.7, 32.64, 42.63), "Boys")
make_pie_chart(c(9.33, 3.83,	11.16,	37.46,	38.22), "Girls")

par(mfrow=c(1, 3)) # Set up a 1x3 grid for plots
plot7 <- make_pie_chart(c(9.92, 3.66, 11.16, 39.54, 35.72), "White only")
plot2 <- make_pie_chart(c(12.8, 3.53, 11.09, 35.4, 37.19), "Asian or Asian American only")
plot8 <- make_pie_chart(c(10.37,3.7,11.12,33.93, 40.89), "Multiple Races")

par(mfrow=c(1, 2)) # Set up a 1x2 grid for plots
plot1 <- make_pie_chart(c(11.98,3.93, 6.96, 14.29, 62.84), "American Indian or Alaskan Native only")
plot6 <- make_pie_chart(c(17.39, 2.48, 6.21, 12.11, 61.8), "Native Hawaiian or Other Pacific Islander only")


par(mfrow=c(1, 3)) # Set up a 1x3 grid for plots
plot3 <- make_pie_chart(c(12.19, 2.1, 6.54, 22, 57.18), "Black, African or African American only")
plot4 <- make_pie_chart(c(14.72, 3.99, 10.13, 24.44, 46.71), "Hispanic or Latino/a only")
plot5 <- make_pie_chart(c(10.03, 2.44, 7.74, 27.22, 52.58), "Middle Eastern or North African")

plot9 <- make_pie_chart(c(3.97, 1.12, 3.61, 10.41, 80.89), "No answer")

```

#difference across regions less than 3%

#Pie Chart race question 5
```{r}
par(mfrow=c(1, 3)) # Set up a 1x3 grid for plots
plot7 <- make_pie_chart(c(9.92, 3.66, 11.16, 39.54, 35.72), "White only")
plot2 <- make_pie_chart(c(12.8, 3.53, 11.09, 35.4, 37.19), "Asian or Asian American only")
plot8 <- make_pie_chart(c(10.37,3.7,11.12,33.93, 40.89), "Multiple Races")

par(mfrow=c(1, 2)) # Set up a 1x2 grid for plots
plot1 <- make_pie_chart(c(11.98,3.93, 6.96, 14.29, 62.84), "American Indian or Alaskan Native only")
plot6 <- make_pie_chart(c(17.39, 2.48, 6.21, 12.11, 61.8), "Native Hawaiian or Other Pacific Islander only")


par(mfrow=c(1, 3)) # Set up a 1x3 grid for plots
plot3 <- make_pie_chart(c(12.19, 2.1, 6.54, 22, 57.18), "Black, African or African American only")
plot4 <- make_pie_chart(c(14.72, 3.99, 10.13, 24.44, 46.71), "Hispanic or Latino/a only")
plot5 <- make_pie_chart(c(10.03, 2.44, 7.74, 27.22, 52.58), "Middle Eastern or North African")

plot9 <- make_pie_chart(c(3.97, 1.12, 3.61, 10.41, 80.89), "No answer")

```














