
# Update data briefs on engagement after school

## Load libraries and data

```{r}
library(readr)
library(dplyr)
library(readxl)
```

```{r}
county_code <- read_csv("complete_county_dict.csv")
```

```{r}
main <- read_csv("../../../STAT112/final/ignite_afterschool/MSS22-3CountyNoRace/MSS22-3CountyNoRace.csv")
data20162022 <- read_csv("../../../STAT112/final/ignite_afterschool/MSS_22-19-16_trend-RaceNoCounty.csv")
what <- read_csv("../../../STAT112/final/ignite_afterschool/MSS_22-19-16_trend-RaceNoCounty.csv")
```
## Assumption

- Answer of "quite a bit" or "very much" to EITHER of A56D(Teachers) or A56E(Other adults at school), which asks how much you feel a specific group cares about you


## Wrangling

```{r}
# Mutate main by county code
main <- main %>% left_join( county_code, 
           by=c('County'='Code'))

main
```

```{r}
A56 <- main %>%
  select(County, A56A, A56B, A56D, A56E, A56F, Region)
```

```{r}
report <- A56 %>%
  group_by(Region) %>%
  mutate(
    caringadult = if_else(A56D > 3 | A56E > 3 | A56F > 3, TRUE, FALSE)
  ) %>%
  summarise(
    total = n(),
    caringadult_true = sum(caringadult == TRUE, na.rm = TRUE),
    caringadult_false = sum(caringadult == FALSE, na.rm = TRUE),
    caringadult_na = sum(is.na(caringadult)),
    percent_true = caringadult_true / total *100,
    percent_false = caringadult_false / total *100,
    percent_unknown = caringadult_na/ total * 100
  ) 

clean_report <- report %>%
  select(Region, percent_true, percent_false, percent_unknown, total) %>% 
  mutate(PctIncreaseInDontCare = case_when(
    Region == "Twin Cities" ~ -1,
    Region == "Central" ~ 3,
    Region == "Northland" ~ 3,
    Region == "Northwest" ~ 2,
    Region == "West Central" ~ 5,
    Region == "Southern" ~ 13,
    Region == "Southwest" ~ 3
  ))

```

## Result
```{r}
write_csv(report, "../result/caringadult_report.csv")
write_csv(clean_report, "../result/clean_caringadult_report.csv")

```


