---
title: "test_new_file"
output: html_document
date: "2024-03-06"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Update data briefs on engagement after school

## Load libraries and data

```{r}
library(readr)
library(dplyr)
library(readxl)
```

```{r}
county_code <- read_csv("complete_county_dict.csv")
```

```{r}
main <- read_csv("../data/MSS22-3CountyNoRace/MSS22-3CountyNoRace.csv")

```

#A16
#A17A-E

## Wrangling

```{r}
# Mutate main by county code
main <- main %>% left_join( county_code, 
           by=c('County'='Code'))

main
```


A16 = num of books in house
A17A = access to internet
A17B = own bedroom
A17C = access to computer
A17D = access to tablet
A17D = access to phone
A50 = has skipped meals because no food
A66A = experienced homelessness


```{r}
income_vars <- main %>%
  select(County, A16, A17A, A17B, A17C, A17D, A17E, A50, A66A, Region)

income_vars
```


```{r}
report <- income_vars %>%
  group_by(Region) %>%
  mutate(
    high_income = if_else(A50==2 | A66A==0, TRUE, FALSE)
  ) %>%
  summarise(
    total = n(),
    high_income_true = sum(high_income == TRUE, na.rm = TRUE),
    high_income_false = sum(high_income == FALSE, na.rm = TRUE),
    high_income_na = sum(is.na(high_income)),
    percent_true = high_income_true / total *100,
    percent_false = high_income_false / total *100,
    percent_unknown = high_income_na/ total * 100
  ) 

clean_report <- report %>%
  select(Region, percent_true, percent_false, percent_unknown, total) %>% 
  mutate(PctIncreaseInDontCare = case_when(
    Region == "Twin Cities" ~ -1,
    Region == "Central" ~ 3,
    Region == "Northland" ~ 3,
    Region == "Northwest" ~ 2,
    Region == "West Central" ~ 5,
    Region == "Southern" ~ 13,
    Region == "Southwest" ~ 3
  ))

```

## Result
```{r}
write_csv(report, "../result/income.csv")
write_csv(clean_report, "../result/clean_income.csv")

```
