---
editor_options: 
  markdown: 
    wrap: 72
---

## Assumption about afterschool activities

Assume that all of the following counts as afterschool activities: - I
stay at my school or go to another school\
- My home or another home such as a friend's, relative's or neighbor's\
- A rec, community or other youth center\
- A park or other outdoor space\
- A library\
- A church, synagogue, mosque, or other spiritual/religious place  

These are A34A, A34B, A34C,.. A34F in the table according to the
codebook.

NA - set default to 0

1- 0 days

2- 1 day

3- 2 days

4- 3 to 4 days

5- 5 days

So

```         
mutate(
    across(starts_with("A34"), ~replace_na(., 0)),
    afterschool = if_else(A34A > 3 | A34B > 3 | A34C > 3 | A34D > 3 | A34E > 3 | A34F > 3, TRUE, FALSE)
)
```

Other wrangling scripts follow similar ideas.

## Making a table named CountyAndRegion.csv

We created a table to look up a county by region in Minnesota called
`county_code_name.csv`. You can look at how we created it by looking at
`ExportCountyName.Rmd`.

Next, use the original table data called `MSS22-3CountyNoRace.csv`, we
join the region code name into it and create a table called
`MSS22-CountyAndRegion.csv`.

```         
MSS22-CountyAndRegion <- MSS22-CountyAndRegion %>% 
  left_join( county_code, by=c('County'='Code'))
write.csv(main, "CountyAndRegion.csv")
```
